// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orders.Data;

#nullable disable

namespace Orders.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20250916100855_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orders.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerName = "Masa",
                            TotalPrice = 99.10m
                        },
                        new
                        {
                            Id = 2,
                            CustomerName = "Worood",
                            TotalPrice = 55.20m
                        },
                        new
                        {
                            Id = 3,
                            CustomerName = "Sara",
                            TotalPrice = 35.99m
                        },
                        new
                        {
                            Id = 4,
                            CustomerName = "Nidal",
                            TotalPrice = 200.20m
                        },
                        new
                        {
                            Id = 5,
                            CustomerName = "Abdullah",
                            TotalPrice = 55.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
